#!/bin/zsh
#
branch="main"
mode="Debug"

git clone -b "$branch" git@github.com:apache/arrow.git --depth 1
cd arrow/cpp && mkdir build && cd build

# install requirements
sudo apt-get install \
     build-essential \
     ninja-build \
     cmake

# normal build with ninja
cmake -GNinja \
  -DCMAKE_BUILD_TYPE="$mode" \
  -DARROW_DATASET=OFF \
  -DARROW_COMPUTE=ON \
  -DARROW_FILESYSTEM=ON \
  -DARROW_JEMALLOC=ON \
  -DARROW_MIMALLOC=ON \
  -DARROW_ORC=OFF \
  -DARROW_PARQUET=OFF \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
  -DARROW_BUILD_EXAMPLES=ON \
  -DARROW_TESTING=OFF \
  -DARROW_BUILD_TESTS=OFF \
  -DARROW_CSV=ON \
  -DARROW_BUILD_BENCHMARKS=OFF \
  -DARROW_FLIGHT=ON \
  -DARROW_WITH_RE2=OFF \
  -DARROW_WITH_SNAPPY=ON \
  -DARROW_WITH_ZLIB=ON \
  -DARROW_WITH_BROTLI=ON \
  -DARROW_WITH_LZ4=ON \
  -DARROW_WITH_ZSTD=ON \
  -DARROW_WITH_BZ2=ON \
  -DARROW_BUILD_OPENMP_BENCHMARKS=OFF \
  -DARROW_BUILD_DETAILED_BENCHMARKS=OFF \
  -DARROW_USE_ASAN=OFF \
  -DARROW_GANDIVA=OFF \
  -DARROW_LLVM_USE_SHARED=OFF \
  -DARROW_TEST_LINKAGE=shared \
  -DARROW_BUILD_SHARED=ON \
  -DARROW_S3=OFF ..

ninja -j16
# sudo ninja install

# cmake .. -DCMAKE_BUILD_TYPE=Release -DARROW_ACERO=OFF -DARROW_DATASET=OFF -DARROW_COMPUTE=ON \
#          -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=OFF -DARROW_ORC=ON -DARROW_PARQUET=ON \
#          -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DARROW_BUILD_EXAMPLES=OFF -DARROW_TESTING=ON \
#          -DARROW_BUILD_TESTS=ON -DARROW_FLIGHT=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON \
#          -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZSTD=ON -DARROW_WITH_BZ2=ON \
#          -DPARQUET_BUILD_EXAMPLES=OFF -DARROW_WITH_RAPIDJSON=ON -DARROW_CSV=ON -DARROW_BUILD_UTILITIES=OFF \
#          -DARROW_JSON=ON -DARROW_BUILD_BENCHMARKS=OFF -DARROW_S3=ON \
#          -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_BUILD_STATIC=OFF \
#          -DProtobuf_SOURCE=SYSTEM -DgRPC_SOURCE=SYSTEM \
#          -DAWSSDK_SOURCE=SYSTEM
# make -j && sudo make install

# arrow-dev normal build
# cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DARROW_DATASET=ON -DARROW_COMPUTE=ON -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=ON \
#   -DARROW_MIMALLOC=ON -DARROW_ORC=OFF -DARROW_PARQUET=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DARROW_BUILD_EXAMPLES=ON \
#   -DARROW_TESTING=ON -DARROW_BUILD_TESTS=ON -DARROW_CSV=ON -DARROW_BUILD_BENCHMARKS=ON -DARROW_FLIGHT=ON -DARROW_WITH_RE2=OFF \
#   -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZSTD=ON -DARROW_WITH_BZ2=ON \
#   -DARROW_BUILD_OPENMP_BENCHMARKS=OFF -DARROW_BUILD_DETAILED_BENCHMARKS=ON -DARROW_USE_ASAN=OFF -DARROW_GANDIVA=OFF -DARROW_LLVM_USE_SHARED=OFF \
#   -DARROW_TEST_LINKAGE=shared -DARROW_BUILD_SHARED=ON -DARROW_S3=OFF -DINSTALL_GTEST=ON -DARROW_SUBSTRAIT=OFF ..

# cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DARROW_DATASET=ON -DARROW_COMPUTE=ON -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=ON \
#   -DARROW_MIMALLOC=ON -DARROW_ORC=OFF -DARROW_PARQUET=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DARROW_BUILD_EXAMPLES=ON \
#   -DARROW_TESTING=ON -DARROW_BUILD_TESTS=ON -DARROW_CSV=ON -DARROW_BUILD_BENCHMARKS=ON -DARROW_FLIGHT=ON -DARROW_WITH_RE2=OFF \
#   -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZSTD=ON -DARROW_WITH_BZ2=ON \
#   -DARROW_BUILD_OPENMP_BENCHMARKS=ON -DARROW_BUILD_DETAILED_BENCHMARKS=ON -DARROW_USE_ASAN=OFF -DARROW_GANDIVA=OFF -DARROW_LLVM_USE_SHARED=OFF \
#   -DARROW_TEST_LINKAGE=shared -DARROW_BUILD_SHARED=ON -DARROW_S3=OFF -DINSTALL_GTEST=ON -DARROW_SUBSTRAIT=OFF -DARROW_WITH_OPENTELEMETRY=ON ..
# ninja -j16

# cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DARROW_DATASET=ON -DARROW_COMPUTE=ON -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=ON \
#   -DARROW_MIMALLOC=ON -DARROW_ORC=OFF -DARROW_PARQUET=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DARROW_BUILD_EXAMPLES=ON \
#   -DARROW_TESTING=ON -DARROW_BUILD_TESTS=ON -DARROW_CSV=ON -DARROW_BUILD_BENCHMARKS=ON -DARROW_FLIGHT=ON -DARROW_WITH_RE2=OFF \
#   -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZSTD=ON -DARROW_WITH_BZ2=ON \
#   -DARROW_BUILD_OPENMP_BENCHMARKS=ON -DARROW_BUILD_DETAILED_BENCHMARKS=ON -DARROW_USE_ASAN=OFF -DARROW_GANDIVA=OFF -DARROW_LLVM_USE_SHARED=OFF \
#   -DARROW_TEST_LINKAGE=shared -DARROW_BUILD_SHARED=ON -DARROW_S3=OFF -DINSTALL_GTEST=ON ..

